# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CovidApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CovidApp

    pod 'SwiftyJSON', '~> 4.0'
    pod "PromiseKit", "~> 6.8"
    pod 'Alamofire', '~> 5.2'

end
