# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Yammer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Yammer

   pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Functions'
  pod 'Firebase/Messaging'
  pod 'Firebase/Storage'
  pod 'Firebase/Database'
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'SwiftSpinner'
  pod 'KeychainSwift', '~> 19.0'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'SDWebImage'
  pod 'SAConfettiView'

end
